# Exercise 15

# Fraud Detection

## Introduction

- Fraud Detection Dataset from Microsoft Azure: [data](http://gallery.cortanaintelligence.com/Experiment/8e9fe4e03b8b4c65b9ca947c72b8e463)

Fraud detection is one of the earliest industrial applications of data mining and machine learning. Fraud detection is typically handled as a binary classification problem, but the class population is unbalanced because instances of fraud are usually very rare compared to the overall volume of transactions. Moreover, when fraudulent transactions are discovered, the business typically takes measures to block the accounts from transacting to prevent further losses. 

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics

In [2]:
import pandas as pd
url = 'https://raw.githubusercontent.com/albahnsen/PracticalMachineLearningClass/master/datasets/15_fraud_detection.csv.zip'
df = pd.read_csv(url, index_col=0)
df.head()

accountAge  digitalItemCount  sumPurchaseCount1Day  sumPurchaseAmount1Day  \
0        2000                 0                     0                   0.00   
1          62                 1                     1                1185.44   
2        2000                 0                     0                   0.00   
3           1                 1                     0                   0.00   
4           1                 1                     0                   0.00   

   sumPurchaseAmount30Day  paymentBillingPostalCode - LogOddsForClass_0  \
0                  720.25                                      5.064533   
1                 2530.37                                      0.538996   
2                    0.00                                      5.064533   
3                    0.00                                      5.064533   
4                  132.73                                      5.412885   

   accountPostalCode - LogOddsForClass_0  \
0                               0.421214   
1                               0.481838   
2                               5.096396   
3                               5.096396   
4                               0.342945   

   paymentBillingState - LogOddsForClass_0  accountState - LogOddsForClass_0  \
0                                 1.312186                          0.566395   
1                                 4.401370                          4.500157   
2                                 3.056357                          3.155226   
3                                 3.331154                          3.331239   
4                                 5.563677                          4.086965   

   paymentInstrumentAgeInAccount  ipState - LogOddsForClass_0  \
0                    3279.574306                     1.218157   
1                      61.970139                     4.035601   
2                       0.000000                     3.314186   
3                       0.000000                     3.529398   
4                       0.001389                     3.529398   

   transactionAmount  transactionAmountUSD  ipPostalCode - LogOddsForClass_0  \
0             599.00            626.164650                          1.259543   
1            1185.44           1185.440000                          3.981118   
2              32.09             32.090000                          5.008490   
3             133.28            132.729554                          1.324925   
4             543.66            543.660000                          2.693451   

   localHour - LogOddsForClass_0  Label  
0                       4.745402      0  
1                       4.921349      0  
2                       4.742303      0  
3                       4.745402      0  
4                       4.876771      0

In [3]:
df.head()

accountAge  digitalItemCount  sumPurchaseCount1Day  sumPurchaseAmount1Day  \
0        2000                 0                     0                   0.00   
1          62                 1                     1                1185.44   
2        2000                 0                     0                   0.00   
3           1                 1                     0                   0.00   
4           1                 1                     0                   0.00   

   sumPurchaseAmount30Day  paymentBillingPostalCode - LogOddsForClass_0  \
0                  720.25                                      5.064533   
1                 2530.37                                      0.538996   
2                    0.00                                      5.064533   
3                    0.00                                      5.064533   
4                  132.73                                      5.412885   

   accountPostalCode - LogOddsForClass_0  \
0                               0.421214   
1                               0.481838   
2                               5.096396   
3                               5.096396   
4                               0.342945   

   paymentBillingState - LogOddsForClass_0  accountState - LogOddsForClass_0  \
0                                 1.312186                          0.566395   
1                                 4.401370                          4.500157   
2                                 3.056357                          3.155226   
3                                 3.331154                          3.331239   
4                                 5.563677                          4.086965   

   paymentInstrumentAgeInAccount  ipState - LogOddsForClass_0  \
0                    3279.574306                     1.218157   
1                      61.970139                     4.035601   
2                       0.000000                     3.314186   
3                       0.000000                     3.529398   
4                       0.001389                     3.529398   

   transactionAmount  transactionAmountUSD  ipPostalCode - LogOddsForClass_0  \
0             599.00            626.164650                          1.259543   
1            1185.44           1185.440000                          3.981118   
2              32.09             32.090000                          5.008490   
3             133.28            132.729554                          1.324925   
4             543.66            543.660000                          2.693451   

   localHour - LogOddsForClass_0  Label  
0                       4.745402      0  
1                       4.921349      0  
2                       4.742303      0  
3                       4.745402      0  
4                       4.876771      0

In [4]:
df.shape, df.Label.sum(), df.Label.mean()

((138721, 16), 797, 0.0057453449730033666)

# Exercise 15.1

Estimate a Logistic Regression and a Decision Tree

Evaluate using the following metrics:
* Accuracy
* F1-Score
* F_Beta-Score (Beta=10)

Comment about the results

In [5]:
y = df['Label']
X = df.drop(['Label'], axis=1)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)


In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, fbeta_score
from sklearn.metrics import confusion_matrix


In [7]:
# Logistic Regression
logreg1 = LogisticRegression(solver='liblinear')  # C=1e9
logreg1.fit(X_train, y_train)

Y_1_a_predictions = logreg1.predict(X_test)
print('\nExercise 15.1_a\n')
print('Accuracy: \n', accuracy_score(y_test, Y_1_a_predictions))
print('f1_Score: \n', f1_score(y_test, Y_1_a_predictions))
print('f_beta_Score: \n', fbeta_score(y_test, Y_1_a_predictions, beta=10))
print('Confusion Matrix: \n', confusion_matrix(y_test, Y_1_a_predictions))



Exercise 15.1_a

Accuracy: 
 0.993949058499716
f1_Score: 
 0.0
f_beta_Score: 
 0.0
Confusion Matrix: 
 [[45501     2]
 [  275     0]]


C:\Users\MLNDGIL\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [8]:
# Tree classifier
from sklearn.tree import DecisionTreeClassifier
treeclf1 = DecisionTreeClassifier(max_depth=None, random_state=1)
treeclf1.fit(X_train, y_train)

print('\nExercise 15.1_b\n')
Y_1_b_predictions = treeclf1.predict(X_test)
print('Accuracy: \n', accuracy_score(y_test, Y_1_b_predictions))
print('f1_Score: \n', f1_score(y_test, Y_1_b_predictions))
print('f_beta_Score: \n', fbeta_score(y_test, Y_1_b_predictions, beta=10))
print('Confusion Matrix: \n', confusion_matrix(y_test, Y_1_b_predictions))




Exercise 15.1_b

Accuracy: 
 0.9886408318406221
f1_Score: 
 0.12457912457912457
f_beta_Score: 
 0.13433265034688524
Confusion Matrix: 
 [[45221   282]
 [  238    37]]


# Exercise 15.2

Under-sample the negative class using random-under-sampling

Which is parameter for target_percentage did you choose?
How the results change?

**Only apply under-sampling to the training set, evaluate using the whole test set**

In [9]:
def UnderSampling(X, y, target_percentage=0.5, seed=None):
   # Assuming minority class is the positive
    n_samples = y.shape[0]
    n_samples_0 = (y == 0).sum()
    n_samples_1 = (y == 1).sum()
    
    n_samples_0_new = n_samples_1 / target_percentage - n_samples_1
    n_samples_0_new_per = n_samples_0_new / n_samples_0

    filter_ = y == 0

    np.random.seed(seed)
    rand_1 = np.random.binomial(n=1, p=n_samples_0_new_per, size=n_samples)

    filter_ = filter_ & rand_1
    filter_ = filter_ | (y == 1)
    filter_ = filter_.astype(bool)

    return X[filter_], y[filter_]


for target_percentage in [0.1, 0.2, 0.3, 0.4, 0.5]:
    X_u, y_u = UnderSampling(X_train, y_train, target_percentage, 1)

In [10]:
 # Logistic Regression
logreg2 = LogisticRegression(solver='liblinear')  # C=1e9
logreg2.fit(X_u, y_u)
    
Y_2_a_predictions = logreg2.predict(X_test)
print('\nExercise 15.2_a, target_percentage=', target_percentage)
print('Accuracy: \n', accuracy_score(y_test, Y_2_a_predictions))
print('f1_Score: \n', f1_score(y_test, Y_2_a_predictions))
print('f_beta_Score: \n', fbeta_score(y_test, Y_2_a_predictions, beta=10))
print('Confusion Matrix: \n', confusion_matrix(y_test, Y_2_a_predictions))

   


Exercise 15.2_a, target_percentage= 0.5
Accuracy: 
 0.572720520774171
f1_Score: 
 0.020628880432605648
f_beta_Score: 
 0.4408331037989703
Confusion Matrix: 
 [[26012 19491]
 [   69   206]]


In [11]:
# Tree classifier
treeclf2 = DecisionTreeClassifier(max_depth=None, random_state=1)
treeclf2.fit(X_u, y_u)
    
print('\nExercise 15.2_b, target_percentage=', target_percentage)
Y_2_b_predictions = treeclf2.predict(X_test)
print('Accuracy: \n', accuracy_score(y_test, Y_2_b_predictions))
print('f1_Score: \n', f1_score(y_test, Y_2_b_predictions))
print('f_beta_Score: \n', fbeta_score(y_test, Y_2_b_predictions, beta=10))
print('Confusion Matrix: \n', confusion_matrix(y_test, Y_2_b_predictions))



Exercise 15.2_b, target_percentage= 0.5
Accuracy: 
 0.6642928917820787
f1_Score: 
 0.023261726198042454
f_beta_Score: 
 0.43024744523848324
Confusion Matrix: 
 [[30227 15276]
 [   92   183]]


# Exercise 15.3

Same analysis using random-over-sampling

In [12]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=42)


In [13]:
X_u, y_u = ros.fit_sample(X_train, y_train)

In [14]:
# Logistic Regression
logreg3 = LogisticRegression(solver='liblinear')  # C=1e9
logreg3.fit(X_u, y_u)

Y_3_a_predictions = logreg3.predict(X_test)
print('\nExercise 15.3_a')
print('Accuracy: \n', accuracy_score(y_test, Y_3_a_predictions))
print('f1_Score: \n', f1_score(y_test, Y_3_a_predictions))
print('f_beta_Score: \n', fbeta_score(y_test, Y_3_a_predictions, beta=10))
print('Confusion Matrix: \n', confusion_matrix(y_test, Y_3_a_predictions))



Exercise 15.3_a
Accuracy: 
 0.601533487701516
f1_Score: 
 0.020722606968379235
f_beta_Score: 
 0.42512867486696326
Confusion Matrix: 
 [[27344 18159]
 [   82   193]]


In [15]:
# Tree classifier
treeclf3 = DecisionTreeClassifier(max_depth=None, random_state=1)
treeclf3.fit(X_u, y_u)

print('\nExercise 15.3_b')
Y_3_b_predictions = treeclf3.predict(X_test)
print('Accuracy: \n', accuracy_score(y_test, Y_3_b_predictions))
print('f1_Score: \n', f1_score(y_test, Y_3_b_predictions))
print('f_beta_Score: \n', fbeta_score(y_test, Y_3_b_predictions, beta=10))
print('Confusion Matrix: \n', confusion_matrix(y_test, Y_3_b_predictions))



Exercise 15.3_b
Accuracy: 
 0.9894709248984228
f1_Score: 
 0.12681159420289853
f_beta_Score: 
 0.12726356337977462
Confusion Matrix: 
 [[45261   242]
 [  240    35]]


# Exercise 15.4 (3 points)

Evaluate the results using SMOTE

Which parameters did you choose?

In [16]:
from imblearn.over_sampling import SMOTE
from collections import Counter

for k in [5, 15]:
    sm = SMOTE(random_state=42, k_neighbors=k)
    X_u, y_u = sm.fit_sample(X_train, y_train)
    print(Counter)


<class 'collections.Counter'>
<class 'collections.Counter'>


In [17]:
# Logistic Regression
logreg4 = LogisticRegression(solver='liblinear')  # C=1e9
logreg4.fit(X_u, y_u)
    
Y_4_a_predictions = logreg4.predict(X_test)
print('\nExercise 15.4_a, k=', k)
print('Accuracy: \n', accuracy_score(y_test, Y_4_a_predictions))
print('f1_Score: \n', f1_score(y_test, Y_4_a_predictions))
print('f_beta_Score: \n', fbeta_score(y_test, Y_4_a_predictions, beta=10))
print('Confusion Matrix: \n', confusion_matrix(y_test, Y_4_a_predictions))



Exercise 15.4_a, k= 15
Accuracy: 
 0.6043732797413605
f1_Score: 
 0.021291542826263176
f_beta_Score: 
 0.4350973102995845
Confusion Matrix: 
 [[27470 18033]
 [   78   197]]


In [18]:
  # Tree classifier
treeclf4 = DecisionTreeClassifier(max_depth=None, random_state=1)
treeclf4.fit(X_u, y_u)
    
print('\nExercise 15.4_b, k=', k)
Y_4_b_predictions = treeclf4.predict(X_test)
print('Accuracy: \n', accuracy_score(y_test, Y_4_b_predictions))
print('f1_Score: \n', f1_score(y_test, Y_4_b_predictions))
print('f_beta_Score: \n', fbeta_score(y_test, Y_4_b_predictions, beta=10))
print('Confusion Matrix: \n', confusion_matrix(y_test, Y_4_b_predictions))



Exercise 15.4_b, k= 15
Accuracy: 
 0.9807112586832103
f1_Score: 
 0.0675818373812038
f_beta_Score: 
 0.11472383927303706
Confusion Matrix: 
 [[44863   640]
 [  243    32]]


# Exercise 15.5 (3 points)

Evaluate the results using Adaptive Synthetic Sampling Approach for Imbalanced
Learning (ADASYN)

http://www.ele.uri.edu/faculty/he/PDFfiles/adasyn.pdf
https://imbalanced-learn.readthedocs.io/en/stable/generated/imblearn.over_sampling.ADASYN.html#rf9172e970ca5-1

In [19]:
from imblearn.over_sampling import ADASYN

for k in [5, 15]:
    ada = ADASYN(random_state=42, n_neighbors=k)
    X_u, y_u = ada.fit_sample(X_train, y_train)
    print(Counter)
    
   

<class 'collections.Counter'>
<class 'collections.Counter'>


In [20]:
  # Logistic Regression
logreg5 = LogisticRegression(solver='liblinear')  # C=1e9
logreg5.fit(X_u, y_u)
    
Y_5_a_predictions = logreg5.predict(X_test)
print('\nExercise 15.5_a, k=', k)
print('Accuracy: \n', accuracy_score(y_test, Y_5_a_predictions))
print('f1_Score: \n', f1_score(y_test, Y_5_a_predictions))
print('f_beta_Score: \n', fbeta_score(y_test, Y_5_a_predictions, beta=10))
print('Confusion Matrix: \n', confusion_matrix(y_test, Y_5_a_predictions))





Exercise 15.5_a, k= 15
Accuracy: 
 0.5554196338852724
f1_Score: 
 0.020408163265306124
f_beta_Score: 
 0.446074040124164
Confusion Matrix: 
 [[25214 20289]
 [   63   212]]


In [22]:
 # Tree classifier
treeclf5 = DecisionTreeClassifier(max_depth=None, random_state=1)
treeclf5.fit(X_u, y_u)
    

print('\nExercise 15.5_b, k=', k)
Y_5_b_predictions = treeclf5.predict(X_test)
print('Accuracy: \n', accuracy_score(y_test, Y_5_b_predictions))
print('f1_Score: \n', f1_score(y_test, Y_5_b_predictions))
print('f_beta_Score: \n', fbeta_score(y_test, Y_5_b_predictions, beta=10))
print('Confusion Matrix: \n', confusion_matrix(y_test, Y_5_b_predictions))



Exercise 15.5_b, k= 15
Accuracy: 
 0.9774127310061602
f1_Score: 
 0.06678700361010831
f_beta_Score: 
 0.131895669360816
Confusion Matrix: 
 [[44707   796]
 [  238    37]]


# Exercise 15.6 (3 points)

Compare and comment about the results

Cuado se revia la situación con el Accuracy el mejor ajuste al modelo se realiza con un arbol de decicón en los dos modelos de SMOTE y ADASYN. Cuando analizamos  el f1_score el menos resultado se visualiza en ADASYN mediante el modelo logistico. 